exec_once:
 files:
  /etc/systemd/system/metabase.service:
    name: metabase.service
    path: /etc/systemd/system/
    mode: "0777"
    owner: root
    group: root
    content: |
      [Unit]
      Description=Metabase
      
      [Service]
      Environment=MB_DB_TYPE=h2
      Environment=MB_DB_FILE=/opt/metabase/metabase.db
      Environment=MB_EMOJI_IN_LOGS=false
      ExecStart=/usr/bin/java -jar /opt/metabase/metabase.jar
      
      [Install]
      WantedBy=multi-user.target
 execs:
  Configure Metabase:
   name: Configure Metabase
   command: |
     #!/usr/bin/env bash
     apt-get install -y default-jre
     wget http://downloads.metabase.com/v0.28.1/metabase.jar
  Enable Metabase Service:
   name: Enable Metabase Service
   command: |
     #!/usr/bin/env bash
     sudo systemctl enable metabase.service
post_app_deploy:
 execs:
  Start metabase:
   name: Start metabase
   command: |
     #!/usr/bin/env bash
     sudo systemctl start metabase.service
